version: "3.7"

services:
   php:
      container_name: bitici-php
      build:
         context: .
         dockerfile: ./Dockerfile.development
      env_file:
         - .env.development
      volumes:
         - ./logs/php:/var/log/php
         - ./logs/php:/usr/share/nginx/html/storage/logs
         - ./source:/usr/share/nginx/html
         - ./conf/development/php.ini:/usr/local/etc/php/php.ini
         - ./conf/docker.conf:/usr/local/etc/php-fpm.d/docker.conf
      networks:
         - bridge

   bitici-development:
      container_name: bitici-development
      image: nginx:latest
      ports:
         - 8000:80
      volumes:
         - ./logs/nginx:/var/log/nginx
         - ./source:/usr/share/nginx/html
         - ./conf/nginx.conf:/etc/nginx/nginx.conf
         - ./conf/development/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
         - php
      networks:
         - bridge

volumes:
   node_modules:

networks:
   bridge:
      driver: bridge
