# Stage 1: Build your PHP application with PHP-FPM
FROM randyproxz/php7.4-fpm-alpine

# Set working directory
WORKDIR /usr/share/nginx/html

# Install mandatory
RUN apk update
RUN apk add --no-cache supervisor tzdata
RUN ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

COPY ./source .

# Start Supervisord to manage programs
COPY ./conf/development/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf", "-n"]