# Start with the openappsec agent image
FROM randyproxz/php7.4-fpm:openappsec

# Update package lists
RUN apk update

# # Create the cache nginx
RUN mkdir -p /var/cache/nginx/fastcgi

COPY ./conf/nginx.conf /etc/nginx/nginx.conf
COPY ./conf/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Verify that the module matches the installed Nginx version
RUN cp /attachment/build_out/nginx_attachment/lib/* /usr/lib
RUN cp /attachment/build_out/nginx_attachment/lib/libngx_module.so /usr/lib/nginx/modules/libngx_module.so
RUN sed -i '1s|^|load_module /usr/lib/nginx/modules/libngx_module.so;\n|' /etc/nginx/nginx.conf

# # Set the default command to run supervisor
# CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]