# Start with the openappsec agent image
FROM ghcr.io/openappsec/agent:latest

RUN apk add --no-cache \
   wget \
   bash \
   git \
   curl-dev \
   openssl-dev \
   gcc \
   g++ \
   make \
   autoconf \
   libc-dev \
   pkgconfig \
   cmake \
   pcre-dev \
   geoip-dev \
   linux-headers \
   python3 \
   perl-dev \
   gd-dev \
   && rm -rf /var/cache/apk/*

# Create the directory for Nginx
RUN mkdir -p /usr/lib/nginx/modules
RUN mkdir -p /var/log/nginx

# Download and extract Nginx 1.22.1 source
RUN curl -O http://nginx.org/download/nginx-1.22.1.tar.gz && \
   tar -xvzf nginx-1.22.1.tar.gz && \
   cd nginx-1.22.1 && \
   ./configure --with-http_ssl_module \
   --prefix=/etc/nginx \
   --conf-path=/etc/nginx/nginx.conf \
   --modules-path=/usr/lib/nginx/modules \
   --http-log-path=/var/log/nginx/access.log \
   --error-log-path=/var/log/nginx/error.log \
   --pid-path=/var/run/nginx.pid && \
   make && \
   make install

# Create symlinks for easier access to the nginx command
RUN ln -s /etc/nginx/sbin/nginx /usr/local/bin/nginx

# Clean up build files
RUN rm -rf nginx-1.22.1.tar.gz nginx-1.22.1

## Capture Nginx version and configuration
RUN nginx -V 2> /tmp/nginx.ver
RUN git clone https://github.com/openappsec/attachment.git attachment
WORKDIR attachment
RUN chmod +x attachments/nginx/ngx_module/nginx_version_configuration.sh
RUN attachments/nginx/ngx_module/nginx_version_configuration.sh --conf /tmp/nginx.ver build_out
RUN cmake -DCMAKE_INSTALL_PREFIX=build_out .
RUN make install
RUN make package

## Copy Advanced model
COPY ./advanced-model/open-appsec-advanced-model.tgz /advanced-model/open-appsec-advanced-model.tgz

## HOW TO USE -------------
# RUN mkdir -p /var/cache/nginx/fastcgi

# COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# COPY ./conf/default.conf /etc/nginx/conf.d/default.conf 

# RUN cp /attachment/build_out/nginx_attachment/lib/* /usr/lib
# RUN cp /attachment/build_out/nginx_attachment/lib/libngx_module.so /usr/lib/nginx/modules/libngx_module.so
# RUN sed -i '1s|^|load_module /usr/lib/nginx/modules/libngx_module.so;\n|' /etc/nginx/nginx.conf
## ------------------------

## ------------------------
## docker build -t randyproxz/openappsec-agent -f Dockerfile.agent .
## ------------------------