version: "3.8"

services:
  openappsec:
    container_name: openappsec
    build:
      context: .
      dockerfile: Dockerfile.agent.test
    volumes:
      - ./source:/usr/share/nginx/html
    entrypoint: /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf -n
    ports:
      - 80:80
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
