# Start with the openappsec agent image
FROM randyproxz/openappsec-agent:nginx

# Add the custom repository for PHP
RUN rm -rf /etc/apk/repositories
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories

# Update package lists
RUN apk update

# Remove any conflicting packages if already installed
RUN apk del boost icu || true

RUN apk add --no-cache \
   build-base \
   wget \
   libpng \
   libpng-dev \
   libjpeg-turbo \
   libjpeg-turbo-dev \
   freetype \
   freetype-dev \
   libzip \
   libzip-dev \
   zlib \
   zlib-dev \
   libxslt-dev \
   libxml2 \
   libxml2-dev \
   curl-dev \
   openssl-dev \
   libsodium-dev \
   oniguruma-dev \
   icu-libs \
   icu-dev \
   gettext-dev \
   bzip2-dev \
   libmemcached-dev \
   dcron \
   gcc \
   g++ \
   make \
   autoconf \
   libc-dev \
   pkgconfig \
   cmake \
   pcre-dev \
   geoip-dev \
   linux-headers \
   python3 \
   perl-dev \
   gd-dev

# Update the apk index and install php81 and php81-fpm
RUN apk add --no-cache \
   php81 \
   php81-fpm \
   php81-opcache \
   php81-mysqli \
   php81-pdo \
   php81-pdo_mysql \
   php81-pgsql \
   php81-mongodb \
   php81-mbstring \
   php81-zlib \
   php81-curl \
   php81-json \
   php81-xml \
   php81-ctype \
   php81-bcmath \
   php81-session \
   php81-soap \
   php81-gd \
   php81-intl \
   php81-gettext \
   php81-xmlrpc \
   php81-pcntl \
   php81-pear \
   php81-mcrypt \
   php81-redis \
   php81-amqp \
   php81-sodium \
   php81-sockets \
   php81-bz2 \
   php81-openssl \
   php81-fileinfo \
   php81-xdebug \
   php81-ftp \
   php81-xmlreader \
   php81-ldap \
   php81-imagick \
   php81-memcached \
   php81-gmp \
   php81-tokenizer \
   php81-pdo_sqlite \
   php81-imap \
   php81-memcached

# Ensure www-data user and group exist, if not already created
RUN getent group www-data || addgroup -S www-data && \
   getent passwd www-data || adduser -S www-data -G www-data

# Ensure www-data user and group exist\
RUN mkdir -p /run/php && chown -R www-data:www-data /run/php

# Copy www.conf to container
COPY ./conf/www.conf /etc/php81/php-fpm.d/www.conf

# Command to run PHP-FPM
CMD ["php-fpm81", "-F"]

## BUILDER ------------------------
## docker build -t randyproxz/php8.1-fpm:openappsec-nginx -f Dockerfile.agent.php81 .
## --------------------------------