# Start with the openappsec agent image
FROM randyproxz/openappsec-agent:nginx

## Create dirs
RUN mkdir -p /var/log/supervisor && chmod 755 /var/log/supervisor
RUN mkdir -p /var/log/nginx && chmod 755 /var/log/nginx

## Copy your files to container
COPY ./conf/default/nginx.conf /etc/nginx/nginx.conf
COPY ./conf/default/default.conf /etc/nginx/conf.d/default.conf
COPY ./conf/default/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

## Load modules
RUN sed -i '1s|^|load_module /usr/lib/nginx/modules/libngx_module.so;\n|' /etc/nginx/nginx.conf