version: "3.8"

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.0.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/log/nginx:/var/log/nginx # Add log
      - /var/log/mariadb:/var/log/mariadb # Add log
    deploy:
      mode: global # Deploy one Filebeat instance per node
    networks:
      - elk-network

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.0.0
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc:/hostfs/proc
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup
      - /:/hostfs
    networks:
      - elk-network

networks:
  elk-network:
    external: true # Connect to the existing ELK stack network
