filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

  # Additional input for specific log paths for MariaDB
  filebeat.inputs:
    # mariaDB log
    - type: log
      enabled: true
      paths:
        - /var/log/mariadb/slow.log
        - /var/log/mariadb/general.log
      fields:
        service: mariadb
      multiline:
        pattern: '^\d{4}-\d{2}-\d{2} '  # Adjust pattern as needed for multiline logs
        negate: true
        match: after

    # Nginx access log
    - type: log
      enabled: true
      paths:
        - /var/log/nginx/access.log
      fields:
        service: nginx
        log_type: access
      multiline:
        pattern: '^\d{4}-\d{2}-\d{2} '
        negate: true
        match: after

output.elasticsearch:
  hosts: ["http://<ELK_SERVER_IP>:9200"]  # Replace with your ELK server IP or hostname [elasticsearch]
  api_key: "filebeat_usr:your_api_key_secret"  # Replace with your actual API key

setup.kibana:
  host: "http://kibana:5601"  # Optional: For direct Kibana setup