metricbeat.modules:
  - module: nginx
    metricsets: ["stubstatus"]
    period: 10s
    hosts: ["http://nginx:80"]

  - module: mysql
    metricsets: ["status"]
    period: 10s
    hosts: ["root:your_password@tcp(mysql:3306)/"]  # Update password and hostname as needed

  - module: system
    metricsets:
      - cpu
      - memory
      - network
      - process
    period: 10s
    processors:
      - add_host_metadata: ~
      - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["http://<ELK_SERVER_IP>:9200"]  # Replace with your ELK server IP or hostname [elasticsearch]
  api_key: "filebeat_usr:your_api_key_secret"  # Replace with your actual API key
