version: "3.7"

services:
   myapp:
      container_name: myapp
      build:
         context: .
         dockerfile: ./Dockerfile
      env_file:
         - .env.development
      command: ["flask", "run", "--host=0.0.0.0", "--debug"]
      ports:
         - 5000:5000
      volumes:
         - ./source:/app
      networks:
         - bridge

networks:
   bridge:
      driver: bridge
