version: "3.8"

services:
  rabbitmq1:
    image: rabbitmq:3-management
    hostname: rabbitmq1
    env_file: .env
    environment:
      - RABBITMQ_NODENAME=rabbit@rabbitmq1
    deploy:
      replicas: 1
      update_config:
        order: start-first
        delay: 1s
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    volumes:
      - ./data/rabbitmq1:/var/lib/rabbitmq
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
    entrypoint: entrypoint.sh
    networks:
      - rabbitmq-network

  rabbitmq2:
    image: rabbitmq:3-management
    hostname: rabbitmq2
    env_file: .env
    environment:
      - RABBITMQ_NODENAME=rabbit@rabbitmq2
      - JOIN_CLUSTER_HOST=rabbitmq1
    depends_on:
      - rabbitmq1
    deploy:
      replicas: 1
      update_config:
        order: start-first
        delay: 1s
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    volumes:
      - ./data/rabbitmq2:/var/lib/rabbitmq
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
    entrypoint: entrypoint.sh
    networks:
      - rabbitmq-network

  rabbitmq3:
    image: rabbitmq:3-management
    hostname: rabbitmq3
    env_file: .env
    environment:
      - RABBITMQ_NODENAME=rabbit@rabbitmq3
      - JOIN_CLUSTER_HOST=rabbitmq1
    depends_on:
      - rabbitmq1
      - rabbitmq2
    deploy:
      replicas: 1
      update_config:
        order: start-first
        delay: 1s
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    volumes:
      - ./data/rabbitmq3:/var/lib/rabbitmq
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
    entrypoint: entrypoint.sh
    networks:
      - rabbitmq-network

  rabbitmq_proxy:
    image: haproxy:alpine
    ports:
      - "5672:5672" # RabbitMQ port
      - "15672:15672" # RabbitMQ Management UI port
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    deploy:
      replicas: 1
      update_config:
        order: start-first
        delay: 1s
      resources:
        limits:
          cpus: "0.2"
          memory: "256M"
    networks:
      - rabbitmq-network

networks:
  rabbitmq-network:
    external: true
