services:
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      UPLOAD_LIMIT: 1G
    ports:
      - "8080:80"
    networks:
      - bridge-ext

networks:
  bridge-ext:
    external: true