---
# Copy all files to container
---

# CI4
ENV COMPOSER_ALLOW_SUPERUSER=1
RUN composer install --working-dir /usr/share/nginx/html/application
RUN chmod -R 777 /usr/share/nginx/html/application/writable

---
# healthcheck
---