version: "3.8"

services:
  consul:
    image: hashicorp/consul:latest
    command: "agent -server -config-file=/consul/config/consul.json -ui -client=0.0.0.0 -bootstrap-expect=1"
    volumes:
      - ./consul-data:/consul/data
      - ./consul.json:/consul/config/consul.json
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.consul.rule=Host(`consul.yourdomain.com`)"
        - "traefik.http.routers.consul.entrypoints=websecure"
        - "traefik.http.routers.consul.tls.certresolver=le"
        - "traefik.http.services.consul.loadbalancer.server.port=8500"
    networks:
      - traefik-network

  vault:
    image: hashicorp/vault:latest
    command: server -config=/vault/config/vault.hcl
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault-data:/vault/file
      - ./vault.hcl/vault/config/vault.hcl
      - ./policies:/vault/policies
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.vault.rule=Host(`vault.yourdomain.com`)"
        - "traefik.http.routers.vault.entrypoints=websecure"
        - "traefik.http.routers.vault.tls.certresolver=le"
        - "traefik.http.services.vault.loadbalancer.server.port=8200"
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true