FROM alpine:3.17

RUN apk update && apk upgrade
RUN apk add \
    bash \
    curl \
    nginx \
    npm

WORKDIR /app

COPY nginx/nginx.conf /etc/nginx
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY package.json .

RUN npm install
COPY . .

EXPOSE 80

CMD ["/bin/bash", "-c", "nginx & npm start"]
