version: "3.4"

services:
  api:
    image: randyproxz/nodejs
    restart: always
    networks:
      - traefik-network
    environment:
      - TZ=Asia/Jakarta
    labels:
      - traefik.enable=true
      - traefik.port=3000
      - traefik.tags=traefik-network
      - traefik.docker.network=traefik-network
      - traefik.frontend.rule=Host:api.domain.com
      - traefik.frontend.entryPoints=http,https
      - traefik.frontend.redirect.entryPoint=https

networks:
  traefik-network:
    external: true
