version: "3.4"

services:
  nodejs:
    image: randyproxz/nodejs
    networks:
      - traefik-network
    environment:
      - TZ=Asia/Jakarta
      - NODE_ENV=production
    command: sh -c "/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf -n"
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        order: start-first
        delay: 1s
      resources:
        reservations:
          cpus: "0.1"
          memory: 100M
        limits:
          cpus: "0.5"
          memory: 500M
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
        max_attempts: 2
      labels:
        - "traefik.enable=true"
        - "traefik.docker.lbswarm=true"
        - "traefik.docker.network=traefik-network"
        
        # http
        - "traefik.http.routers.app-production-http.rule=Host(`app.com`,`www.app.com`)"
        - "traefik.http.routers.app-production-http.entrypoints=web"

        # https
        - "traefik.http.routers.app-production.rule=Host(`app.com`,`www.app.com`)"
        - "traefik.http.routers.app-production.entrypoints=websecure"
        - "traefik.http.routers.app-production.tls=true"
        - "traefik.http.routers.app-production.tls.options=default"
        - "traefik.http.routers.app-production.tls.certresolver=le"

        # Service
        - "traefik.http.services.app-production.loadbalancer.server.port=3000"
        - "traefik.http.services.app-production.loadbalancer.sticky.cookie=true"
        - "traefik.http.services.app-production.loadbalancer.sticky.cookie.httpOnly=true"
        - "traefik.http.services.app-production.loadbalancer.sticky.cookie.name=app"
        - "traefik.http.services.app-production.loadbalancer.sticky.cookie.secure=true"

        # Middleware for http
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.routers.app-production-http.middlewares=redirect-to-https"

        # Middleware for https
        - "traefik.http.routers.app-production.middlewares=default-middlewares@file"

networks:
  traefik-network:
    external: true
