FROM node:20-alpine

# Install apk alpine
RUN apk --update --no-cache add curl tzdata

# Set Timezone
RUN ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

# Set Environment
ENV PATH /app/node_modules/.bin:$PATH

WORKDIR /app

# Copy your files to container
COPY ./source/package.json .
RUN npm install

EXPOSE 3000

CMD [ "npm", "run", "dev" ]