version: "3.4"

services:
  nextjs-dev:
    build:
      context: .
      dockerfile: ./Dockerfile.development
    volumes:
      - ./source:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - TZ=Asia/Jakarta
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: yarn dev
    ports:
      - 3000:3000
    networks:
      - bridge

networks:
  bridge:
    driver: bridge