version: '3'

services:
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - db-network

  phppgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    volumes:
      - ./data_pgadmin:/var/lib/pgadmin/data
    ports:
      - 8080:80
    depends_on:
      - postgres
    networks:
      - db-network

networks:
  db-network:
    external: true