version: '3'

services:
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - bridge
      - postgres

  phppgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    volumes:
       - ./servers.json:/pgadmin4/servers.json # preconfigured servers/connections
    ports:
      - 8080:80
    depends_on:
      - postgres
    networks:
      - bridge
      - postgres

networks:
  postgres:
    external: true
  bridge:
    driver: bridge