version: "3.4"

services:
  myapp-php:
    image: docker.io/randyproxz/php:latest
    restart: always
    networks:
      - traefik-network
    volumes:
      - /var/log/nginx:/var/log/nginx # mkdir -p /var/log/nginx
      - /var/log/cron.log:/var/log/cron.log # mkdir -p /var/log/cron.log && chmod 777 /var/log/cron.log
    environment:
      - TZ=Asia/Jakarta
    # # Deploy is using docker-swarm
    # deploy:
    #   # mode: global
    #   mode: replicated
    #   replicas: 1
    #   update_config:
    #     parallelism: 1
    #     order: start-first
    #     failure_action: rollback
    #     delay: 10s
    #   restart_policy:
    #     condition: any
    #     delay: 5s
    #     max_attempts: 1
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:php.domain.com
      - traefik.tags=traefik-network
      - traefik.docker.network=traefik-network
      - traefik.frontend.entryPoints=http,https
      - traefik.frontend.redirect.entryPoint=https

networks:
  traefik-network:
    external: true
