version: "3.7"

services:
  php:
    container_name: myapp-php
    image: randyproxz/php7.4-fpm-alpine
    env_file:
      - .env.development
    volumes:
      - ./logs/php:/var/log/php
      - ./source:/usr/share/nginx/html
      - ./conf/development/php.ini:/usr/local/etc/php/php.ini
      - ./conf/docker.conf:/usr/local/etc/php-fpm.d/docker.conf
    networks:
      - bridge

  myapp-nginx:
    container_name: myapp-nginx
    depends_on:
      - myapp-php
    image: nginx:latest
    env_file:
      - .env.development
    ports:
      - 80:80
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./source:/usr/share/nginx/html
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/development/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bridge
      
  myapp-cron:
    container_name: myapp-cron
    image: randyproxz/php7.4-fpm-alpine
    env_file:
      - .env.development
    volumes:
      - ./logs/cron:/var/log/cron
      - ./source:/usr/share/nginx/html
      - ./conf/cron/crontab:/crontab
      - ./conf/cron/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    command: sh -c "/usr/bin/crontab /crontab && /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf -n"
    networks:
      - bridge

networks:
  bridge:
    driver: bridge