version: "3.7"

services:
  myapp-php:
    container_name: myapp-php
    image: randyproxz/php7.4-fpm-alpine
    environment:
      - CI_ENV=development
      - TZ=Asia/Jakarta
    volumes:
      - ./logs/php:/var/log/php
      - ./source:/usr/share/nginx/html
      - ./conf/development/php.ini:/usr/local/etc/php/php.ini
      - ./conf/docker.conf:/usr/local/etc/php-fpm.d/docker.conf
    networks:
      - bridge

  myapp-development:
    container_name: myapp-development
    depends_on:
      - myapp-php
    image: nginx:latest
    environment:
      - CI_ENV=development
      - TZ=Asia/Jakarta
    ports:
      - 80:80
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./source:/usr/share/nginx/html
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/development/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bridge

      
  myapp-cron:
    container_name: myapp-cron
    image: randyproxz/php7.4-fpm-alpine
    environment:
      - CI_ENV=development
      - TZ=Asia/Jakarta
    volumes:
      - ./logs/cron:/var/log/cron
      - ./source:/usr/share/nginx/html
      - ./conf/development/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    command: sh -c "cat /usr/share/nginx/html/cron >> /etc/crontabs/root && /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf -n"
    networks:
      - bridge

networks:
  bridge:
    driver: bridge