version: "3.7"

services:

  myapp-production:
    image: randyproxz/php7.4-fpm-alpine:production
    networks:
      - traefik-network
    environment:
      - CI_ENV=production
      - TZ=Asia/Jakarta
    volumes:
      - /var/log/nginx:/var/log/nginx
      - /var/log/php:/var/log/php
      - /tmp:/tmp
    deploy:
      # mode: global
      mode: replicated
      replicas: 3
      # update_config:
      #   parallelism: 3
      #   order: start-first
      #   failure_action: rollback
      #   delay: 1s
      # restart_policy:
      #   condition: any
      #   delay: 20s
      #   max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.app-production.rule=Host(`php.domain.com`)"
        - "traefik.http.routers.app-production.entrypoints=websecure"
        - "traefik.http.routers.app-production.tls=true"
        - "traefik.http.routers.app-production.tls.options=intermediate@file"
        - "traefik.http.routers.app-production.tls.certresolver=le"
        - "traefik.http.routers.app-production.middlewares=default-middlewares"
        - "traefik.http.services.app-production.loadbalancer.server.port=80"

  # myapp-cron:
  #   image: randyproxz/php7.4-fpm-alpine:production
  #   environment:
  #     - CI_ENV=production
  #     - TZ=Asia/Jakarta
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #   volumes:
  #     - /var/log/cron:/var/log/cron
  #   command: sh -c "cat /usr/share/nginx/html/cron >> /etc/crontabs/root && /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf -n"
  #   networks:
  #     - traefik-network

networks:
  traefik-network:
    external: true
