version: "3.4"

services:
  php:
    image: docker.io/randyproxz/php:latest
    restart: always
    networks:
      - traefik-network
    environment:
      - TZ=Asia/Jakarta
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.frontend.rule=Host:php.domain.com
      - traefik.tags=traefik-network
      - traefik.docker.network=traefik-network
      - traefik.frontend.entryPoints=http,https
      - traefik.frontend.redirect.entryPoint=https

networks:
  traefik-network:
    external: true
