version: "3.7"

services:

  app-production:
    image: randyproxz/php7.4-fpm-alpine:production
    networks:
      - traefik-network
    environment:
      - CI_ENV=production
      - TZ=Asia/Jakarta
    volumes:
      - /var/log/nginx:/var/log/nginx # mkdir -p /var/log/nginx
      - /var/log/php-fpm.log:/var/log/php-fpm.log
      # - /tmp:/tmp
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost/healthcheck"]
    #   interval: 10s 
    #   timeout: 10s
    #   retries: 10
    deploy:
      # mode: global
      mode: replicated
      replicas: 3
      # update_config:
      #   parallelism: 3
      #   order: start-first
      #   failure_action: rollback
      #   delay: 1s
      # restart_policy:
      #   condition: any
      #   delay: 20s
      #   max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.app-production.rule=Host(`php.domain.com`)"
        - "traefik.http.routers.app-production.entrypoints=websecure"
        - "traefik.http.routers.app-production.tls=true"
        - "traefik.http.routers.app-production.tls.options=intermediate@file"
        - "traefik.http.routers.app-production.tls.certresolver=le"
        - "traefik.http.services.app-production.loadbalancer.server.port=80"

  app-cron:
    image: randyproxz/php7.4-fpm-alpine:production
    environment:
      - CI_ENV=production
      - TZ=Asia/Jakarta
    deploy:
      mode: replicated
      replicas: 1
    command: 
      - sh
      - -c
      - |
        /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf -n &
        /usr/share/nginx/html/entrypoint.sh
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
