version: "3.8"

services:
  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
